# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-21 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=128, null=True, unique=True, verbose_name='\u8bbe\u5907\u540d')),
                ('device_number', models.CharField(max_length=128, unique=True, verbose_name='\u8bbe\u5907\u7f16\u53f7')),
                ('Warranty', models.SmallIntegerField(verbose_name='\u4fdd\u4fee\u671f')),
                ('buy_time', models.CharField(blank=True, max_length=128, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('buy_type', models.SmallIntegerField(blank=True, choices=[(1, '\u516c\u53f8\u5185\u8d2d'), (2, '\u5458\u5de5\u81ea\u8d2d')], verbose_name='\u8d2d\u4e70\u65b9\u5f0f')),
                ('price', models.IntegerField(blank=True, verbose_name='\u8d2d\u4e70\u4ef7\u683c')),
                ('suse_time', models.DateField(max_length=128, null=True, verbose_name='\u5f00\u59cb\u4f7f\u7528\u65f6\u95f4')),
                ('euse_time', models.DateField(max_length=128, null=True, verbose_name='\u622a\u81f3\u4f7f\u7528\u65f6\u95f4')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, '\u6b63\u5728\u4f7f\u7528'), (2, '\u672a\u4f7f\u7528'), (3, '\u8bbe\u5907\u6545\u969c'), (4, '\u5e93\u5b58\u5907\u7528')], verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u8d44\u4ea7\u521b\u5efa\u65f6\u95f4')),
                ('devicetag', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7\u8868\u7ba1\u7406',
                'verbose_name_plural': '\u8d44\u4ea7\u8868\u7ba1\u7406',
                'permissions': (('cmdb_assets_view', 'Can view \u8d44\u4ea7\u8868\u7ba1\u7406'), ('assets_index_view', '\u8d44\u4ea7\u7ba1\u7406')),
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True, verbose_name='\u4e1a\u52a1\u540d')),
                ('memo', models.CharField(blank=True, max_length=64, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1\u5217\u8868',
                'verbose_name_plural': '\u4e1a\u52a1\u5217\u8868',
                'permissions': (('cmdb_devicetype_view', 'Can view \u4e1a\u52a1\u5217\u8868'),),
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=64, verbose_name='UUID\u53f7')),
                ('parent_sn', models.CharField(blank=True, max_length=128, verbose_name='\u670d\u52a1\u5668SN')),
                ('Architecture', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u67b6\u6784')),
                ('Vendor', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u578b\u53f7')),
                ('cpu_mhz', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u9891\u7387')),
                ('L1cache', models.CharField(blank=True, max_length=128, null=True)),
                ('L2cache', models.CharField(blank=True, max_length=128, null=True)),
                ('L3cache', models.CharField(blank=True, max_length=128, null=True)),
                ('Thread', models.SmallIntegerField(null=True, verbose_name='\u7ebf\u7a0b')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPU',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u7c7b\u578b',
                'verbose_name_plural': '\u8bbe\u5907\u7c7b\u578b',
                'permissions': (('cmdb_devicetype_view', 'Can view \u8bbe\u5907\u7c7b\u578b'),),
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='\u786c\u76d8\u540d\u79f0')),
                ('uuid', models.CharField(blank=True, max_length=128, unique=True)),
                ('parent_sn', models.CharField(blank=True, max_length=128, verbose_name='\u670d\u52a1\u5668SN')),
                ('Firm', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5236\u9020\u5546')),
                ('capacity', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bb9\u91cf')),
                ('disk_type', models.SmallIntegerField(blank=True, choices=[(1, 'SATA'), (2, 'SSD')], null=True, verbose_name='\u78c1\u76d8\u7c7b\u578b')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': '\u786c\u76d8',
                'verbose_name_plural': '\u786c\u76d8',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(blank=True, max_length=128, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u697c\u5c42')),
                ('contacts', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'IDC',
                'verbose_name_plural': 'IDC',
                'permissions': (('cmdb_idc_view', 'Can view IDC'),),
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=128, verbose_name='UUID\u53f7')),
                ('parent_sn', models.CharField(blank=True, max_length=128, verbose_name='\u670d\u52a1\u5668SN')),
                ('name', models.CharField(max_length=128, verbose_name='\u7f51\u5361\u540d\u79f0')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u578b\u53f7')),
                ('ip', models.GenericIPAddressField(default='', verbose_name='IP\u5730\u5740')),
                ('mac', models.CharField(max_length=64, verbose_name='mac\u5730\u5740')),
                ('netmask', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('nicstatus', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f51\u5361\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': '\u7f51\u5361',
                'verbose_name_plural': '\u7f51\u5361',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=128, unique=True, verbose_name='\u63d0\u4f9b\u5546')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='\u5730\u5740')),
                ('contacts', models.CharField(blank=True, max_length=128, verbose_name='\u8054\u7cfb\u4eba')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('Fax', models.CharField(blank=True, max_length=20, verbose_name='\u4f20\u771f')),
            ],
            options={
                'verbose_name': '\u4f9b\u5e94\u5546',
                'verbose_name_plural': '\u4f9b\u5e94\u5546',
                'permissions': (('cmdb_provider_view', 'Can view \u4f9b\u5e94\u5546'),),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='SN\u53f7')),
                ('hostname', models.CharField(max_length=128, verbose_name='\u4e3b\u673a\u540d')),
                ('mem', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u5b58\u603b\u5bb9\u91cf')),
                ('swap', models.CharField(blank=True, max_length=128, null=True, verbose_name='swap\u5bb9\u91cf')),
                ('platform', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5e73\u53f0')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7cfb\u7edf')),
                ('version', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7248\u672c')),
                ('Firm', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5236\u9020\u5546')),
                ('cpu_count', models.SmallIntegerField(blank=True, verbose_name='cpu\u4e2a\u6570')),
                ('cpu_core_count', models.SmallIntegerField(blank=True, verbose_name='cpu\u6838\u6570')),
                ('raid', models.CharField(blank=True, max_length=128, null=True, verbose_name='RAID\u7ea7\u522b')),
                ('saltid', models.CharField(blank=True, max_length=128, null=True, verbose_name='SaltID\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('addtype', models.SmallIntegerField(blank=True, choices=[(1, '\u624b\u52a8\u6dfb\u52a0'), (2, '\u81ea\u52a8\u91c7\u96c6')], default=1, verbose_name='\u91c7\u96c6\u6a21\u5f0f')),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('Assets', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub', to='servermanager.Assets', verbose_name='\u8d44\u4ea7\u5173\u8054')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servermanager.Cpu')),
                ('disk', models.ManyToManyField(blank=True, to='servermanager.Disk', verbose_name='\u786c\u76d8')),
                ('nic', models.ManyToManyField(to='servermanager.NIC', verbose_name='\u7f51\u5361\u5217\u8868')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u7ba1\u7406',
                'verbose_name_plural': '\u670d\u52a1\u5668\u7ba1\u7406',
                'permissions': (('cmdb_server_view', 'Can view \u670d\u52a1\u5668\u7ba1\u7406'),),
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='\u8f6f\u4ef6\u540d\u79f0')),
                ('version', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7248\u672c')),
                ('license', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5e8f\u5217\u53f7')),
            ],
            options={
                'verbose_name': '\u8f6f\u4ef6\u7ba1\u7406',
                'verbose_name_plural': '\u8f6f\u4ef6\u7ba1\u7406',
                'permissions': (('cmdb_software_view', 'Can view \u8f6f\u4ef6\u7ba1\u7406'),),
            },
        ),
        migrations.AddField(
            model_name='server',
            name='software',
            field=models.ManyToManyField(blank=True, to='servermanager.Software', verbose_name='\u8f6f\u4ef6\u5217\u8868'),
        ),
        migrations.AddField(
            model_name='assets',
            name='IDC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servermanager.IDC'),
        ),
    ]
