# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-21 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servermanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7ba1\u7406\u5458\u90ae\u7bb1'),
        ),
        migrations.AddField(
            model_name='assets',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servermanager.Business', verbose_name='\u4e1a\u52a1'),
        ),
        migrations.AddField(
            model_name='assets',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servermanager.DeviceType', verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='assets',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servermanager.Provider', verbose_name='\u63d0\u4f9b\u5546'),
        ),
    ]
