# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0002_auto_20161121_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='uuid',
            field=models.CharField(max_length=64, verbose_name='UUID\u53f7'),
        ),
    ]
