# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0003_auto_20161128_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='parent_sn',
            field=models.CharField(max_length=128, verbose_name='\u670d\u52a1\u5668SN'),
        ),
    ]
