# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0004_auto_20161128_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='idc_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
