# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0005_auto_20161128_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u4e1a\u52a1\u540d'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u786c\u76d8\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='parent_sn',
            field=models.CharField(max_length=128, verbose_name='\u670d\u52a1\u5668SN'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='uuid',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='nic',
            name='parent_sn',
            field=models.CharField(max_length=128, verbose_name='\u670d\u52a1\u5668SN'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='uuid',
            field=models.CharField(max_length=128, verbose_name='UUID\u53f7'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u63d0\u4f9b\u5546'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u8f6f\u4ef6\u540d\u79f0'),
        ),
    ]
