# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0006_auto_20161128_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='contacts',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8054\u7cfb\u4eba'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='idc_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='IDC'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
    ]
