# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0008_auto_20161128_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='saltid',
            field=models.CharField(max_length=128, verbose_name='SaltID\u540d'),
        ),
    ]
