# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-02 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0010_auto_20161128_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='nic',
            field=models.ManyToManyField(blank=True, to='servermanager.NIC', verbose_name='\u7f51\u5361\u5217\u8868'),
        ),
    ]
